name: aify
description: "App concept of AI generated music library. "
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Load svg icons
  flutter_svg: ^2.0.10+1

  # State management system
  get: ^4.6.6

  # Load google fonts
  google_fonts: ^6.2.1

  # Load custom animated video
  rive: ^0.13.13

  # Create basic animations
  simple_animations: ^5.0.2

  # Authentication and database access
  supabase_flutter: ^2.6.0

  # URL launcher
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  dart_define: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/default/
    - assets/icons/white/
    - assets/images/
    - assets/images/backgrounds/
    - assets/animations/
    - assets/fonts/

dart_define:

    dart: true 
    json: true
    json_path: env.json
    dart_path: lib/env.gen.dart 
    class_name: Environments 

    variables: 

        - name: SUPABASE_URL
          description: Put your supabase url here

        - name: SUPABASE_ANON_KEY
          description: Put your supabase anon key here

        - name: DEBUG
          description: Enable debug
          required: false
          default: false
