// This file was generated by package:dart_define, DO NOT modify or remove these comments
class Environments {
  Environments._();
  
  /// Put your supabase url here
  static const supabaseUrl = String.fromEnvironment('SUPABASE_URL');

  /// Put your supabase anon key here
  static const supabaseAnonKey = String.fromEnvironment('SUPABASE_ANON_KEY');

  /// Enable debug
  static const debug = bool.fromEnvironment('DEBUG');
}

    